[Variables]
;original colors 
;Color1=126,154,250,225
;Color2=255,160,32,225
; Color1 is the left
; Color2 is the right
; 	A transparency value of 175-225 is recommended

Color1=119,136,153,210
Color2=47,65,65,175

TextFont=Open Sans Light
TextFontLight=Roboto Light
NumeralFont=Titillium Web ExtraLight

; Warning: Skin will not dynamically adjust to font size (yet...)
; If adjusting fonts, also remember to adjust font size if necessary!
HeaderFontSize=14
DateFontSize=11
CompanyFontSize=11
RocketFontSize=10
DescFontSize=9